### ISSUE TITLE
GEPRIS viewer: info text

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/gepris-viewer#19]
WISSEN: Legend "Anzahl Forschungsprojekte" -> top right corner

Top left: Info text
Diese Visualisierung basiert auf Informationen zu Forschungsprojekten, die von der Deutschen Forschungsgemeinschaft (DFG) gefördert wurden. Quelle: 
https://gepris.dfg.de

**Comment by lillijo** [comment]
So?

![Screenshot from 2020-05-28 17-53-36](https://user-images.githubusercontent.com/38139300/83164198-39d28980-a10c-11ea-8152-96a1f93789d4.png)
